In [116]:
import pandas as pd
import numpy as np
import os
from itertools import combinations
import datacompy

folder_path = r'C:\Users\hoa.nd\Desktop\WAP\compare\report_4\result'

In [117]:
def read_or_load_excel(file_path,save_path,sheet_name=None):
  try:
    df=pd.read_pickle(save_path)
  except FileNotFoundError:
    df= pd.read_excel(file_path,dtype=str,sheet_name=sheet_name)
    df.to_pickle(save_path)
  return df

In [118]:
df_cognos_bl = read_or_load_excel(r"C:\Users\hoa.nd\Desktop\WAP\compare\report_4\folder1\(OTS analysis) Over 330 days BL-EUA.xlsx",'df_cognos_bl.pkl','Over 365 days bal')
df_cognos_bl

,Country,Collection Office Code,Customer Code,Customer Name,BL Number,Over 330 Days (USD),Over 330 Days Overpayment (USD),Over 330 Days Partially applied (USD),Over 330 Days Pure Outstanding (USD),Customer BL Outstanding (USD),Positive / Negative Over 330 Days Bal (USD)
0,AUSTRIA,VNABB,AT100054,BTG SPEDITION UND LOGISTIK GMBH,JKTC81219500,0.01,0,0.01,0,0.01,Positive
1,AUSTRIA,VNABB,AT100351,PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.,RICA08831500,478.45,0,0,478.45,478.45,Positive
2,BELGIUM,ANRBB,BE100849,KUEHNE & NAGEL NV,ANRA06645600,0.01,0,0.01,0,0.01,Positive
3,BELGIUM,ANRBB,BE500222,HET ANKER BROKERS,CPTC05570300,1841.54,0,0,1841.54,1841.54,Positive
4,BELGIUM,ANRBB,BE500222,HET ANKER BROKERS,CPTC03565500,3978.29,0,3978.29,0,3978.29,Positive
...,...,...,...,...,...,...,...,...,...,...,...
6716,TURKEY,MERBA,TR511220,FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLE...,MERC06095600,130,0,130,0,130,Positive
6717,UNITED KINGDOM,SOUBB,GB101805,KUEHNE & NAGEL LIMITED,CPTC35779300,12994.98,0,0,12994.98,12994.98,Positive
6718,UNITED KINGDOM,SOUBB,GB101809,KUEHNE & NAGEL LIMITED,NB1BS2292800,4622,0,0,4622,4622,Positive
6719,UNITED KINGDOM,SOUBB,GB101809,KUEHNE & NAGEL LIMITED,NB1BCGV06300,8624,0,0,8624,8624,Positive
6720,UNITED KINGDOM,SOUBB,GB104948,KUEHNE & NAGEL LIMITED,CPTB17411600,5463,0,0,5463,5463,Positive

In [119]:
df_cognos_in = read_or_load_excel(r"C:\Users\hoa.nd\Desktop\WAP\compare\report_4\folder1\(OTS analysis) Over 330 days BL-EUA.xlsx",'df_cognos_in.pkl','Over 365 days inv no.')

In [120]:
df_looker_bl = read_or_load_excel(r"C:\Users\hoa.nd\Desktop\WAP\compare\report_4\folder1\Looker - Over 365 days bal.xlsx",'df_looker_bl.pkl','sheet1')

In [121]:
df_looker_in = read_or_load_excel(r"C:\Users\hoa.nd\Desktop\WAP\compare\report_4\folder1\Looker - Over 365 days inv no.xlsx",'df_looker_in.pkl','sheet1')
df_looker_in

,Region-TGC3,Collection Region Name,Collection Office Code,Actual Customer Code,Actual Customer Name,BL Number,Aging Days,Actual Invoice Number,Invoice Issue Date1,Invoice Due Date1,Is DEM/DET (Yes / No),Is DMT I/F ERP (Yes / No),Ageing,Over 365 Days (USD)-TGC3,OTS Group Name,OTS Type Name,OTS Remarks
0,EUA,GHANA,TEMBB,AE510533,MEMAAR BUILDING SYSTEMS FZC,TEM22BCD0002,417 days,TEM22BCD0002ORG,2022-11-03,2022-11-03,No,Yes,Over 1 year,841.15,BAD,Claim,Damage container fee. Claims team are followin...
1,EUA,AUSTRIA,VNABB,AT100002,GEBRUEDER WEISS GESELLSCHAFT M.B.H.,SH1UN2897300,440 days,NaN,NaN,2022-10-11,No,Yes,Over 1 year,0,NaN,NaN,NaN
2,EUA,AUSTRIA,VNABB,AT100054,BTG SPEDITION UND LOGISTIK GMBH,JKTC81219500,412 days,ATR014541,2022-10-25,2022-11-08,Yes,Yes,Over 1 year,0.01,ACT,Rate Dispute,under clarification csv
3,EUA,AUSTRIA,VNABB,AT100065,CARGO-PARTNER GMBH,NB1BCGE91800,630 days,NaN,NaN,2022-04-04,No,Yes,Over 1 year,0,NaN,NaN,NaN
4,EUA,AUSTRIA,VNABB,AT100066,CARGO-PARTNER GMBH,HKGCD3253600,380 days,NaN,NaN,2022-12-10,No,Yes,Over 1 year,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,EUA,UKRAINE,ODSBA,UA501793,ADENA-AGRO LLC,SZ0HI0377900,1194 days,NaN,NaN,2020-09-17,No,Yes,Over 3 years,0,NaN,NaN,NaN
10344,EUA,UKRAINE,ODSBA,UA501850,PODOLSKIY PROMETEY PRIVATE ENTERPRISE,TA0PVC263500,1125 days,NaN,NaN,2020-11-25,No,Yes,Over 3 years,0,NaN,NaN,NaN
10345,EUA,UKRAINE,ODSBA,UA501871,SES PRIMORSKE LLC,TA9DX2280400,1145 days,NaN,NaN,2020-11-05,No,Yes,Over 3 years,0,NaN,NaN,NaN
10346,EUA,SOUTH AFRICA,CPTBB,ZA200475,DSV SOUTH AFRICA (PTY) LTD AIR & SEA,NB0BH6636400,1137 days,NaN,NaN,2020-11-13,No,Yes,Over 3 years,0,NaN,NaN,NaN
10347,EUA,NIGERIA,LOSBB,ZA500002,KIDS II SOUTH AFRICA PTY LTD,NB8IJ5446300,1186 days,NGT024207,2020-09-25,2020-09-25,Yes,No,Over 3 years,2333.94,BAD,No Reply From Customers,"Genuine outstanding, will continue to chase cu..."

In [122]:
df_cognos_bl.columns

Index(['Country', 'Collection Office Code', 'Customer Code', 'Customer Name',
       'BL Number', 'Over 330 Days (USD)', 'Over 330 Days Overpayment (USD)',
       'Over 330 Days Partially applied (USD)',
       'Over 330 Days Pure Outstanding (USD)', 'Customer BL Outstanding (USD)',
       'Positive / Negative Over 330 Days Bal (USD)'],
      dtype='object')

In [123]:
df_looker_bl.columns

Index(['Collection Region Name', 'Collection Office Code',
       'Actual Customer Code', 'Actual Customer Name', 'BL Number',
       'Over 365 Days (USD)-TGC3', 'Overpayment (USD)', 'Shortpayment (USD)',
       'Pure Outstanding (USD)', 'Outstanding Amount (USD)',
       'Positive / Negative Over 330 Days Bal (USD)'],
      dtype='object')

In [124]:
COGNOS_TO_LOOKER_BL={
  'Country':'Collection Region Name',
  'Customer Code':'Actual Customer Code',
  'Customer Name':'Actual Customer Name',
  'Over 330 Days (USD)':'Over 365 Days (USD)-TGC3',
  'Over 330 Days Overpayment (USD)':'Overpayment (USD)',
  'Over 330 Days Partially applied (USD)':'Shortpayment (USD)',
  'Over 330 Days Pure Outstanding (USD)':'Pure Outstanding (USD)',
  'Customer BL Outstanding (USD)':'Outstanding Amount (USD)',
}

df_cognos_bl.rename(columns=COGNOS_TO_LOOKER_BL, inplace=True)
df_cognos_bl

,Collection Region Name,Collection Office Code,Actual Customer Code,Actual Customer Name,BL Number,Over 365 Days (USD)-TGC3,Overpayment (USD),Shortpayment (USD),Pure Outstanding (USD),Outstanding Amount (USD),Positive / Negative Over 330 Days Bal (USD)
0,AUSTRIA,VNABB,AT100054,BTG SPEDITION UND LOGISTIK GMBH,JKTC81219500,0.01,0,0.01,0,0.01,Positive
1,AUSTRIA,VNABB,AT100351,PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.,RICA08831500,478.45,0,0,478.45,478.45,Positive
2,BELGIUM,ANRBB,BE100849,KUEHNE & NAGEL NV,ANRA06645600,0.01,0,0.01,0,0.01,Positive
3,BELGIUM,ANRBB,BE500222,HET ANKER BROKERS,CPTC05570300,1841.54,0,0,1841.54,1841.54,Positive
4,BELGIUM,ANRBB,BE500222,HET ANKER BROKERS,CPTC03565500,3978.29,0,3978.29,0,3978.29,Positive
...,...,...,...,...,...,...,...,...,...,...,...
6716,TURKEY,MERBA,TR511220,FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLE...,MERC06095600,130,0,130,0,130,Positive
6717,UNITED KINGDOM,SOUBB,GB101805,KUEHNE & NAGEL LIMITED,CPTC35779300,12994.98,0,0,12994.98,12994.98,Positive
6718,UNITED KINGDOM,SOUBB,GB101809,KUEHNE & NAGEL LIMITED,NB1BS2292800,4622,0,0,4622,4622,Positive
6719,UNITED KINGDOM,SOUBB,GB101809,KUEHNE & NAGEL LIMITED,NB1BCGV06300,8624,0,0,8624,8624,Positive
6720,UNITED KINGDOM,SOUBB,GB104948,KUEHNE & NAGEL LIMITED,CPTB17411600,5463,0,0,5463,5463,Positive

In [125]:
df_looker_bl

,Collection Region Name,Collection Office Code,Actual Customer Code,Actual Customer Name,BL Number,Over 365 Days (USD)-TGC3,Overpayment (USD),Shortpayment (USD),Pure Outstanding (USD),Outstanding Amount (USD),Positive / Negative Over 330 Days Bal (USD)
0,UNITED KINGDOM,SOUBB,GB504778,QUALITY FREIGHT SERVICES LIMITED,SZPCT3788600,0,0,0,0,0,Negtive
1,UNITED KINGDOM,SOUBB,GB206450,YES 2 SHIP LIMITED,SZPCV5529300,0,0,0,0,0,Negtive
2,UNITED KINGDOM,SOUBB,GB103028,UNIEXPRESS LIMITED,TA2ZB4705800,0,0,0,0,0,Negtive
3,UNITED KINGDOM,SOUBB,GB105930,SPRAY SHIPPING LIMITED,TA2VT4340600,0,0,0,0,0,Negtive
4,UNITED KINGDOM,SOUBB,GB101809,KUEHNE & NAGEL LIMITED,SGNCB5858300,0,0,0,0,0,Negtive
...,...,...,...,...,...,...,...,...,...,...,...
10715,NETHERLANDS,RTMBB,NL504230,SHPP B.V.,RICCEK390600,0,0,0,0,0,Negtive
10716,NETHERLANDS,RTMBB,NL100640,DACHSER NETHERLANDS AIR & SEA LOGISTICS B.V.,CJBA00152700,0,0,0,0,0,Negtive
10717,NETHERLANDS,RTMBB,NL100190,APEX SHIPPING B.V.,JKTC66881600,0,0,0,0,0,Negtive
10718,NETHERLANDS,RTMBB,RO501117,VERSUNI MANUFACTURING ROMANIA S.R.L.,CNDC00224800,-75,-75,0,0,-75,Negtive
10719,NETHERLANDS,RTMBB,NL504230,SHPP B.V.,RICCEN144600,0,0,0,0,0,Negtive

In [126]:

LIST_COLUMN=['Collection Region Name', 'Collection Office Code',
  'Actual Customer Code', 'Actual Customer Name', 'BL Number',
  'Over 365 Days (USD)-TGC3', 'Overpayment (USD)', 'Shortpayment (USD)',
  'Pure Outstanding (USD)', 'Outstanding Amount (USD)',
  'Positive / Negative Over 330 Days Bal (USD)']
REMOVE_COLUMN=['Over 365 Days (USD)-TGC3','Overpayment (USD)','Shortpayment (USD)','Pure Outstanding (USD)','Outstanding Amount (USD)']

keys_list = [x for x in list(LIST_COLUMN) if x not in REMOVE_COLUMN]

grouped_cognos_df = df_cognos_bl.groupby(keys_list)[REMOVE_COLUMN].sum()
grouped_cognos_df

# compare = datacompy.Compare( df_cognos_bl, df_looker_bl, join_columns=keys_list, df1_name='Cognos', df2_name='Looker')
# print(compare.report())

                                                                                                                                                                               Over 365 Days (USD)-TGC3  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                               BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100054             BTG SPEDITION UND LOGISTIK GMBH                    JKTC81219500 Positive                                                        0.01
                                              AT100351             PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.        RICA08831500 Positive                                                      478.45
BELGIUM                ANRBB                  BE100849             KUEHNE & NAGEL NV                                  ANRA06645600 Positive                                                        0.01
                                              BE500222             HET ANKER BROKERS                                  CPTC03565500 Positive                                                     3978.29
                                                                                                                      CPTC05570300 Positive                                                     1841.54
...                                                                                                                                                                                                 ...
TURKEY                 MERBA                  TR511220             FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLER... MERC06095600 Positive                                                         130
UNITED KINGDOM         SOUBB                  GB101805             KUEHNE & NAGEL LIMITED                             CPTC35779300 Positive                                                    12994.98
                                              GB101809             KUEHNE & NAGEL LIMITED                             NB1BCGV06300 Positive                                                        8624
                                                                                                                      NB1BS2292800 Positive                                                        4622
                                              GB104948             KUEHNE & NAGEL LIMITED                             CPTB17411600 Positive                                                        5463

                                                                                                                                                                               Overpayment (USD)  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                               BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100054             BTG SPEDITION UND LOGISTIK GMBH                    JKTC81219500 Positive                                                    0
                                              AT100351             PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.        RICA08831500 Positive                                                    0
BELGIUM                ANRBB                  BE100849             KUEHNE & NAGEL NV                                  ANRA06645600 Positive                                                    0
                                              BE500222             HET ANKER BROKERS                                  CPTC03565500 Positive                                                    0
                                                                                                                      CPTC05570300 Positive                                                    0
...                                                                                                                                                                                          ...
TURKEY                 MERBA                  TR511220             FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLER... MERC06095600 Positive                                                    0
UNITED KINGDOM         SOUBB                  GB101805             KUEHNE & NAGEL LIMITED                             CPTC35779300 Positive                                                    0
                                              GB101809             KUEHNE & NAGEL LIMITED                             NB1BCGV06300 Positive                                                    0
                                                                                                                      NB1BS2292800 Positive                                                    0
                                              GB104948             KUEHNE & NAGEL LIMITED                             CPTB17411600 Positive                                                    0

                                                                                                                                                                               Shortpayment (USD)  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                               BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100054             BTG SPEDITION UND LOGISTIK GMBH                    JKTC81219500 Positive                                                  0.01
                                              AT100351             PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.        RICA08831500 Positive                                                     0
BELGIUM                ANRBB                  BE100849             KUEHNE & NAGEL NV                                  ANRA06645600 Positive                                                  0.01
                                              BE500222             HET ANKER BROKERS                                  CPTC03565500 Positive                                               3978.29
                                                                                                                      CPTC05570300 Positive                                                     0
...                                                                                                                                                                                           ...
TURKEY                 MERBA                  TR511220             FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLER... MERC06095600 Positive                                                   130
UNITED KINGDOM         SOUBB                  GB101805             KUEHNE & NAGEL LIMITED                             CPTC35779300 Positive                                                     0
                                              GB101809             KUEHNE & NAGEL LIMITED                             NB1BCGV06300 Positive                                                     0
                                                                                                                      NB1BS2292800 Positive                                                     0
                                              GB104948             KUEHNE & NAGEL LIMITED                             CPTB17411600 Positive                                                     0

                                                                                                                                                                               Pure Outstanding (USD)  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                               BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100054             BTG SPEDITION UND LOGISTIK GMBH                    JKTC81219500 Positive                                                         0
                                              AT100351             PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.        RICA08831500 Positive                                                    478.45
BELGIUM                ANRBB                  BE100849             KUEHNE & NAGEL NV                                  ANRA06645600 Positive                                                         0
                                              BE500222             HET ANKER BROKERS                                  CPTC03565500 Positive                                                         0
                                                                                                                      CPTC05570300 Positive                                                   1841.54
...                                                                                                                                                                                               ...
TURKEY                 MERBA                  TR511220             FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLER... MERC06095600 Positive                                                         0
UNITED KINGDOM         SOUBB                  GB101805             KUEHNE & NAGEL LIMITED                             CPTC35779300 Positive                                                  12994.98
                                              GB101809             KUEHNE & NAGEL LIMITED                             NB1BCGV06300 Positive                                                      8624
                                                                                                                      NB1BS2292800 Positive                                                      4622
                                              GB104948             KUEHNE & NAGEL LIMITED                             CPTB17411600 Positive                                                      5463

                                                                                                                                                                               Outstanding Amount (USD)
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                               BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100054             BTG SPEDITION UND LOGISTIK GMBH                    JKTC81219500 Positive                                                        0.01
                                              AT100351             PANALPINA WELTTRANSPORT GESELLSCHAFT M.B.H.        RICA08831500 Positive                                                      478.45
BELGIUM                ANRBB                  BE100849             KUEHNE & NAGEL NV                                  ANRA06645600 Positive                                                        0.01
                                              BE500222             HET ANKER BROKERS                                  CPTC03565500 Positive                                                     3978.29
                                                                                                                      CPTC05570300 Positive                                                     1841.54
...                                                                                                                                                                                                 ...
TURKEY                 MERBA                  TR511220             FOREVER FORWARDER LOJISTIK DENIZCILIK HIZMETLER... MERC06095600 Positive                                                         130
UNITED KINGDOM         SOUBB                  GB101805             KUEHNE & NAGEL LIMITED                             CPTC35779300 Positive                                                    12994.98
                                              GB101809             KUEHNE & NAGEL LIMITED                             NB1BCGV06300 Positive                                                        8624
                                                                                                                      NB1BS2292800 Positive                                                        4622
                                              GB104948             KUEHNE & NAGEL LIMITED                             CPTB17411600 Positive                                                        5463

[6721 rows x 5 columns]

In [127]:
grouped_looker_df = df_looker_bl.groupby(keys_list)[REMOVE_COLUMN].sum()
grouped_looker_df

                                                                                                                                                                 Over 365 Days (USD)-TGC3  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                 BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100002             GEBRUEDER WEISS GESELLSCHAFT M.B.H.  SH1UN2897300 Negtive                                                            0
                                              AT100054             BTG SPEDITION UND LOGISTIK GMBH      JKTC81219500 Positive                                                        0.01
                                              AT100065             CARGO-PARTNER GMBH                   NB1BCGE91800 Negtive                                                            0
                                              AT100066             CARGO-PARTNER GMBH                   HKGCD3253600 Negtive                                                            0
                                              AT100089             DACHSER AUSTRIA AIR & SEA GMBH       TPEB97690300 Negtive                                                            0
...                                                                                                                                                                                   ...
UNITED KINGDOM         SOUBB                  GB509981             OAK FURNITURELAND GROUP LIMITED      SGNC69570900 Negtive                                                            0
                                                                                                        SGNC69570901 Negtive                                                            0
                                              GB510392             MAERSK LOGISTICS AND SERVICES UK LTD XMNC90916300 Negtive                                                            0
                                                                                                        XMNC90920500 Negtive                                                            0
                                                                                                        XMNC90926400 Negtive                                                            0

                                                                                                                                                                 Overpayment (USD)  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                 BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100002             GEBRUEDER WEISS GESELLSCHAFT M.B.H.  SH1UN2897300 Negtive                                                     0
                                              AT100054             BTG SPEDITION UND LOGISTIK GMBH      JKTC81219500 Positive                                                    0
                                              AT100065             CARGO-PARTNER GMBH                   NB1BCGE91800 Negtive                                                     0
                                              AT100066             CARGO-PARTNER GMBH                   HKGCD3253600 Negtive                                                     0
                                              AT100089             DACHSER AUSTRIA AIR & SEA GMBH       TPEB97690300 Negtive                                                     0
...                                                                                                                                                                            ...
UNITED KINGDOM         SOUBB                  GB509981             OAK FURNITURELAND GROUP LIMITED      SGNC69570900 Negtive                                                     0
                                                                                                        SGNC69570901 Negtive                                                     0
                                              GB510392             MAERSK LOGISTICS AND SERVICES UK LTD XMNC90916300 Negtive                                                     0
                                                                                                        XMNC90920500 Negtive                                                     0
                                                                                                        XMNC90926400 Negtive                                                     0

                                                                                                                                                                 Shortpayment (USD)  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                 BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100002             GEBRUEDER WEISS GESELLSCHAFT M.B.H.  SH1UN2897300 Negtive                                                      0
                                              AT100054             BTG SPEDITION UND LOGISTIK GMBH      JKTC81219500 Positive                                                  0.01
                                              AT100065             CARGO-PARTNER GMBH                   NB1BCGE91800 Negtive                                                      0
                                              AT100066             CARGO-PARTNER GMBH                   HKGCD3253600 Negtive                                                      0
                                              AT100089             DACHSER AUSTRIA AIR & SEA GMBH       TPEB97690300 Negtive                                                      0
...                                                                                                                                                                             ...
UNITED KINGDOM         SOUBB                  GB509981             OAK FURNITURELAND GROUP LIMITED      SGNC69570900 Negtive                                                      0
                                                                                                        SGNC69570901 Negtive                                                      0
                                              GB510392             MAERSK LOGISTICS AND SERVICES UK LTD XMNC90916300 Negtive                                                      0
                                                                                                        XMNC90920500 Negtive                                                      0
                                                                                                        XMNC90926400 Negtive                                                      0

                                                                                                                                                                 Pure Outstanding (USD)  \
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                 BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100002             GEBRUEDER WEISS GESELLSCHAFT M.B.H.  SH1UN2897300 Negtive                                                          0
                                              AT100054             BTG SPEDITION UND LOGISTIK GMBH      JKTC81219500 Positive                                                         0
                                              AT100065             CARGO-PARTNER GMBH                   NB1BCGE91800 Negtive                                                          0
                                              AT100066             CARGO-PARTNER GMBH                   HKGCD3253600 Negtive                                                          0
                                              AT100089             DACHSER AUSTRIA AIR & SEA GMBH       TPEB97690300 Negtive                                                          0
...                                                                                                                                                                                 ...
UNITED KINGDOM         SOUBB                  GB509981             OAK FURNITURELAND GROUP LIMITED      SGNC69570900 Negtive                                                          0
                                                                                                        SGNC69570901 Negtive                                                          0
                                              GB510392             MAERSK LOGISTICS AND SERVICES UK LTD XMNC90916300 Negtive                                                          0
                                                                                                        XMNC90920500 Negtive                                                          0
                                                                                                        XMNC90926400 Negtive                                                          0

                                                                                                                                                                 Outstanding Amount (USD)
Collection Region Name Collection Office Code Actual Customer Code Actual Customer Name                 BL Number    Positive / Negative Over 330 Days Bal (USD)
AUSTRIA                VNABB                  AT100002             GEBRUEDER WEISS GESELLSCHAFT M.B.H.  SH1UN2897300 Negtive                                                            0
                                              AT100054             BTG SPEDITION UND LOGISTIK GMBH      JKTC81219500 Positive                                                        0.01
                                              AT100065             CARGO-PARTNER GMBH                   NB1BCGE91800 Negtive                                                            0
                                              AT100066             CARGO-PARTNER GMBH                   HKGCD3253600 Negtive                                                            0
                                              AT100089             DACHSER AUSTRIA AIR & SEA GMBH       TPEB97690300 Negtive                                                            0
...                                                                                                                                                                                   ...
UNITED KINGDOM         SOUBB                  GB509981             OAK FURNITURELAND GROUP LIMITED      SGNC69570900 Negtive                                                            0
                                                                                                        SGNC69570901 Negtive                                                            0
                                              GB510392             MAERSK LOGISTICS AND SERVICES UK LTD XMNC90916300 Negtive                                                            0
                                                                                                        XMNC90920500 Negtive                                                            0
                                                                                                        XMNC90926400 Negtive                                                            0

[7158 rows x 5 columns]